-- 1. todas los alumnos que teninen gmail
SELECT * FROM ALUMNOS WHERE CORREO LIKE '%gmail%';
-- 2. Todos los alumnos (nombre, apellido paterno. apellido materno) que hayan cursado en el 2002
SELECT NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO FROM ALUMNOS 
JOIN ALUMNOS_NIVELES ON ALUMNOS.ID = ALUMNOS_NIVELES.ALUMNO_ID WHERE FECHA_CURSADA=2002;
-- 3. Todos los grados donde su ubicación  sea el sotano o segunto piso
SELECT * FROM niveles WHERE UBICACION IN('Sotano', 'Segundo Piso');
-- 4. todos los grados (seccion, y el nombre)que han tenido alumnos en el 2003
SELECT SECCION, NOMBRE, FECHA_CURSADA AS AÑO FROM NIVELES INNER JOIN ALUMNOS_NIVELES ON NIVELES.ID = ALUMNOS_NIVELES.NIVEL_ID WHERE FECHA_CURSADA = 2003;

-- NOTA: SI NO TIENEN ESAS SECCIONES USAR SECCIONES QUE SI TENGAN
-- 5. MOSTRAR TODOS LOS ALUMNOS DE QUINTO A 
-- 6. MOSTRAR TODOS LOS CORREOS DE LOS ALUMNOS DEL PRIMERO B


